name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: |
        cd client
        npm install
        cd ../server
        npm install
    - name: Run integration tests
      working-directory: client
      run: npm run test:integration
    - name: Run unit tests and generate coverage report
      working-directory: client
      run: |
        npm run test:unit
        npm run test:coverage
